# Generated by Django 4.1.5 on 2023-06-09 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('venta', '0003_alter_producto_descripcion_alter_usuario_rut'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='rut',
            field=models.CharField(db_column='rutUsuario', max_length=12, primary_key=True, serialize=False),
        ),
    ]
