# Generated by Django 4.1.2 on 2023-06-28 21:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('venta', '0004_alter_usuario_rut'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='codigo_producto',
            field=models.AutoField(db_column='codigoProducto', primary_key=True, serialize=False),
        ),
        migrations.CreateModel(
            name='Carrito',
            fields=[
                ('codigo_carrito', models.AutoField(db_column='codigoCarrito', primary_key=True, serialize=False)),
                ('cantidad', models.IntegerField()),
                ('producto', models.CharField(max_length=25)),
                ('estado', models.CharField(max_length=10)),
                ('codigo_producto', models.ForeignKey(db_column='codigoProducto', on_delete=django.db.models.deletion.CASCADE, to='venta.producto')),
                ('rut', models.ForeignKey(db_column='rutUsuario', on_delete=django.db.models.deletion.CASCADE, to='venta.usuario')),
            ],
        ),
    ]
