# Generated by Django 4.1.2 on 2023-07-10 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('venta', '0007_alter_producto_cantidad_stock_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='precio',
            field=models.IntegerField(),
        ),
    ]
