# Generated by Django 4.1.2 on 2023-07-10 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('venta', '0008_alter_producto_precio'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
